from environments.level_based_foraging.agents import ClosestAppleForager
from environments.predator_prey.agents import GreedyPredator, TeammateAwarePredator

from environments.observation_functions import DefaultFeatures, GrayscaleFeatures, FieldOfViewChannels

from environments.LevelBasedForaging import LevelBasedForaging
from environments.PredatorPrey import PredatorPrey
